#!/usr/bin/env python3
import sys, os, os.path
import callcatcher

args = sys.argv[1:]

if len(args) == 0:
	print('Usage: e.g. callcatcher gcc test.c -o test')
else:
	#--hijack gcc/g++ and detect output file
	if sys.argv.count('-c'):
		callcatcher.compile(args)
	else:
		# https://gcc.gnu.org/wiki/Response_Files, read all @file to callcatcher
		expands = []
		for arg in args:
			if arg.startswith('@'):
				try:
					with open(arg[1:], 'r') as f:
						c = f.read()
						ex = c.split(' ')
						expands += ex
				except Exception as e:
					print(e)
		final_args = []
		for arg in args:
			if arg[0] != '@':
				final_args.append(arg)
		final_args += expands
		callcatcher.link(final_args)
	#--call original invocation---
	program = ''
	for arg in sys.argv[1:]:
		program = program + ' ' + callcatcher.shellquote(arg)
	os.execvp(sys.argv[1], sys.argv[1:])
