#!/usr/bin/env python3
import sys, os, os.path
import callcatcher

args = sys.argv[1:]

if len(args) == 0:
	print('Usage: e.g. callcatcher gcc test.c -o test')
else:
	#--hijack gcc/g++ and detect output file
	if sys.argv.count('-c'):
		callcatcher.compile(args)
	else:
		# https://gcc.gnu.org/wiki/Response_Files, read all @file to callcatcher
		for i in range(len(args)):
			arg = args[i]
			if arg.startswith('@'):
				try:
					with open(arg[1:], 'r') as f:
						args[i] = f.read()
				except Exception as e:
					print(e)
		final_args = ' '.join(args).split(' ')
		callcatcher.link(final_args)
	#--call original invocation---
	program = ''
	for arg in sys.argv[1:]:
		program = program + ' ' + callcatcher.shellquote(arg)
	os.execvp(sys.argv[1], sys.argv[1:])
